### ISSUE TITLE
Not sure about view.php

### ISSUE THREAD

**Issue by mudrd8mz** [nhoobin/moodle-auth_enrolkey#3]
I am quite unsure about view.php. I think I understand how it is supposed to work, but I have two concerns:

* As the file starts with `defined('MOODLE_INTERNAL') || die;` I am pretty sure that it ends with simply white blank screen after the browser is redirected to it.
* What is the reasoning of passing the token to view.php via $SESSION? I can see some, just want to be sure.

Can you please double check that this functionality works as expected? I may be missing something. Thanks.

**Comment by nhoobin** [comment]
I have modified it so that `defined('MOODLE_INTERNAL') || die;` is no longer present. It now checks for `require_login();` and if the session has passed a list of enrolment plugin ids in `$SESSION->availableenrolids`

This list of available enrol ids is generated from checking if the enrolment key matches any enrolment instance, and that it is possible to enrol from checking via the `can_self_enrol()` method.

Passing the token/enrolment key password was used in older iterations to acquire the list of plugin instances that used that specific key. Now that it passes a list of the enrolment plugin ids, the token is not longer required.
